variables:
  HTTP_PROXY: $HTTP_PROXY
  HTTPS_PROXY: $HTTPS_PROXY

before_script:
  - docker info

stages:
  - build
  - push

build_image:
  stage: build
  script:
    - docker build --rm -t "$CI_REGISTRY_IMAGE" . --build-arg $HTTP_PROXY --build-arg $HTTPS_PROXY

push_image:
  stage: push
  script:
    - docker tag "$CI_REGISTRY_IMAGE" $REG_TARGET:5000/"$CI_REGISTRY_IMAGE"
    - docker login --username $DOCKER_USER --password $DOCKER_PASSWORD $REG_TARGET:5000
    - docker push $REG_TARGET:5000/"$CI_REGISTRY_IMAGE"
#    - docker run my-docker-image /script/to/run/tests

