version: '2'

services:
  mariadb:
   image: mariadb
   hostname: mariadb
   environment:
    - MYSQL_ROOT_PASSWORD=root-password
    - MYSQL_DATABASE=wikka
    - MYSQL_USER=wikka
    - MYSQL_PASSWORD=wikka-password
   volumes:
     - $PWD/mysql:/var/lib/mysql

  wiki:
   image: oems/wikkawiki:latest
   links:
     - mariadb
   ports:
     - '80:80'
